apiVersion: apps/v1
kind: Deployment
metadata:
  name: warp-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: warp-api
  template:
    metadata:
      labels:
        app: warp-api
    spec:
      containers:
      - name: api
        image: christophergaughan/warp-api:latest
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: warp-config
        - secretRef:
            name: aws-creds

