name: Deploy Monitoring Stack

on:
  push:
    paths:
      - 'monitoring/terraform/**'
    branches:
      - main
  workflow_dispatch:  # Manual trigger option

jobs:
  deploy-monitoring:
    uses: ./.github/workflows/terraform.yml
    with:
      aws-region: us-east-2

