name: Deploy Monitoring Stack

on:
  push:
    paths:
      - 'monitoring/terraform/**'
    branches:
      - main
  workflow_dispatch:  # Manual trigger option

jobs:
  deploy-monitoring:
    uses: ./.github/workflows/terraform.yml
    with:
      aws-region: us-east-2
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

