name: Run PCA in Docker

on:
  workflow_dispatch:

jobs:
  run-pca:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Docker
      run: docker build -t feature-engineering ./docker

    - name: Run PCA container
      run: |
        docker run --rm \
          -e INPUT_PATH="s3://omicflow-data-bucket/expression_matrix.csv" \
          -e METADATA_PATH="s3://omicflow-data-bucket/cell_metadata.csv" \
          -e OUTPUT_PATH="pca_results.csv" \
          -e S3_OUTPUT_PATH="s3://omicflow-data-bucket/results/pca_results.csv" \
          -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
          -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
          -e AWS_DEFAULT_REGION="us-east-2" \
          feature-engineering

